created Run() and handler by specefication .yaml
Denisz0785/learning-postgreSQL pull request #5
Opened 2024-04-07 08:33 UTC by Denisz0785

2024-04-09 13:57 UTC, Aidamir requested changes

2024-04-09 13:57 UTC, Aidamir commented on repository/repository.go
> +func (r *ExpenseRepo) GetIdExpenseUser(ctx context.Context, id int) ([]string, error) {
Этот метод не нужен, нужно добавить. в GetTypesExpenseUser колонку id. Какая была идея отдельного метода для получения id? Чем меньше запросов мы делаем к БД тем у нас быстрее работает БД.

2024-04-09 13:57 UTC, Aidamir commented on server/expense_handlers.go
> +		expenseRepo := repository.ExpenseRepo(*r)
Не нужно делать обработчик http запроса методом репозитория . Идея как раз состоит в том чтобы разделить эти два разных слоя . Где ты такое увидел?

2024-04-09 13:57 UTC, Aidamir commented on server/expense_handlers.go
> +		for i := 0; i < len(titleExpense); i++ {
порядок данных  expense_types которые вернут эти запросы будет произвольным поскольку в методах в SQL не указывается order by поэтому здесь коды и заголовки могут не соответствовать. Я тебе уже написал в другом комменте что нужно просто один метод сделать .

2024-04-09 13:57 UTC, Aidamir commented on server/expense_handlers.go
> +		for i := 0; i < len(titleExpense); i++ {
порядок данных  expense_types которые вернут эти запросы будет произвольным поскольку в методах в SQL не указывается order by поэтому здесь коды и заголовки могут не соответствовать. Я тебе уже написал в другом комменте что нужно просто один метод сделать .

2024-04-09 14:13 UTC, Denisz0785 commented on repository/repository.go
> +func (r *ExpenseRepo) GetIdExpenseUser(ctx context.Context, id int) ([]string, error) {
сначала я пытался получить title и id в одном методе, но при компиляции вылезала ошибка, что функция Query возвращает один вид значений, а я пытаюсь отправить два.
поэтому вместо одного метода, я сделал два.
а как можно вернуть в один срез значения по нескольким столбцам в одном методе?)

2024-04-09 14:19 UTC, Denisz0785 commented on server/expense_handlers.go
> +		for i := 0; i < len(titleExpense); i++ {
понял, что нужно сделать один метод. я писал выше, что сначала пытался так сделать...)

2024-04-09 17:08 UTC, Aidamir commented on repository/repository.go
> +func (r *ExpenseRepo) GetIdExpenseUser(ctx context.Context, id int) ([]string, error) {
Создай пакет dto и в нем помести структуры нужные для возврата данных методами репозитория в хендлеры или же параметры для методов их тоже можно передавать в структурах

2024-04-09 17:11 UTC, Aidamir commented on server/expense_handlers.go
> +		expenseRepo := repository.ExpenseRepo(*r)
Где здесь дублироание не могу понять . Хендлер вызывает методы репозитория где дублирование?

2024-04-09 17:14 UTC, Denisz0785 commented on repository/repository.go
> +func (r *ExpenseRepo) GetIdExpenseUser(ctx context.Context, id int) ([]string, error) {
увидел твой коммент только сейчас. уже переделал по-другому. изменения запушил, но второй ПР почему-то сделать не могу. тебе видны изменения или нет?

2024-04-09 17:16 UTC, Denisz0785 commented on server/expense_handlers.go
> +		expenseRepo := repository.ExpenseRepo(*r)
что-то я немного запутался. как делать правильно: методы репозитория могут использовать в хэндлерах или лучше не делать таких зависимостей? )

2024-04-09 17:35 UTC, Aidamir commented on server/expense_handlers.go
> +		expenseRepo := repository.ExpenseRepo(*r)
а зачем они нужны тогда если их не использовать в хендлерах ? Не пойму твою идею о зависимостях какие зависимости конкретно ты имеешь ввиду?

2024-04-09 18:33 UTC, Denisz0785 commented on server/expense_handlers.go
> +		expenseRepo := repository.ExpenseRepo(*r)
> Не нужно делать обработчик http запроса методом репозитория . Идея как раз состоит в том чтобы разделить эти два разных слоя . Где ты такое увидел?

эту фразу я понял так, что в хэндлерах не нужно использовать методы, объявленные в репозитории. или ты имел ввиду что-то другое?)

2024-04-09 18:34 UTC, Denisz0785 commented on server/expense_handlers.go
> +		expenseRepo := repository.ExpenseRepo(*r)
и еще...что значит:"разделить 2 разных слоя", для чего и как это делается?
извини за глупые вопросы)

2024-04-11 07:14 UTC, Aidamir requested changes

2024-04-11 07:14 UTC, Aidamir commented on server/expense_handlers.go
> +	conn *repository.ExpenseRepo
Почему conn? а не repo? это же не соединение с БД а репозиторий

2024-04-11 07:14 UTC, Aidamir commented on repository/repository.go
> +type repo interface {
Было нормальноe  имя repository одинаковое с пакетом . И этот интерфейс нужно как раз экспортировать

2024-04-21 08:27 UTC, Aidamir requested changes
Переделай пож-ста в соответствии с комментами код

2024-04-21 08:27 UTC, Aidamir commented on dto_expenses/dto.go
>  type User struct {
На мой взгляд User слишком двусмысленно лучше привязать к функции - TypesExpenseUserParams
Есть неофициальное соглашение модели в dto которые используются в качестве параметров именовать по такой схеме [method name]Params

2024-04-21 08:27 UTC, Aidamir commented on repository/repository.go
> -	numbers, err := pgx.CollectRows(rows, pgx.RowTo[string])
Код выполнения запроса и обработки ошибки продублирован 3 раза - этого можно избежать если сделать сначала генерацию SQL а затем выполнить однажды запрос

2024-04-28 10:58 UTC, Aidamir requested changes

2024-04-28 10:58 UTC, Aidamir commented on repository/repository.go
> +	if d.Id != 0 {
Ты сделал так что для того чтобы сделать. фильтр по имени пользователя нужно передать id , login , name а какой в этом смысл? Надо сделать так чтобы условие конструировалось из первого непустого поля структуры например если передаем  {id: 0, login: "", name:"vasya"}  условие будет таким WHERE  name = 'vasya' если {id: 1, login: "", name:"vasya"} то WHERE id = 1

2024-04-28 10:58 UTC, Aidamir commented on repository/repository.go
> +		rows, _ := r.conn.Query(ctx, "SELECT id, title from expense_type where expense_type.users_id=$1", d.Id)
Та часть запроса SQL которая не изменяется во всех 3 запросах не должна повторяться к ней нужно прибавлять разные условия по ходу выполнения "SELECT id, title from expense_type E where"

2024-04-28 10:58 UTC, Aidamir commented on server/expense_handlers.go
> +				fmt.Fprintf(w, "Uncorrect value of id%v", err)
Здесь не надо return?

2024-04-28 11:27 UTC, Aidamir requested changes

2024-04-28 11:27 UTC, Aidamir commented on server/expense_handlers.go
> +	err = r.repo.AddFileExpense(ctx, filePath, expenseID)
Сначала создал файл потом проверил расширение и выдал ошибку ? Прекрасно! Lets run file upload attack!)) Можно забить весь диск сервера хламовыми файлами)

2024-04-28 11:27 UTC, Aidamir commented on server/expense_handlers.go
> +		exist, err := r.repo.IsExpenseExists(ctx, expenseID)
А если в промежутке после того как ты проверил и вызвал repo.AddFileExpense оно будет удалено?

2024-04-28 16:33 UTC, Denisz0785 commented on repository/repository.go
> +	if d.Id != 0 {
понял, но сейчас это так и работает. Я пробовал через Postman. Условие конструируется из первого непустого поля. Для того чтобы получить ответ за запрос по имени не обяз-но, чтобы передавались id и login. Запрос будет выполнен даже если будет передан только один из трех параметров.

2024-04-28 17:00 UTC, Denisz0785 commented on server/expense_handlers.go
> +	err = r.repo.AddFileExpense(ctx, filePath, expenseID)
исправил) сейчас сначала проверяет расширение, потом создает папку, записывает на диск и потом в БД

2024-04-28 17:25 UTC, Denisz0785 commented on server/expense_handlers.go
> +		exist, err := r.repo.IsExpenseExists(ctx, expenseID)
исправил, чтобы проверка и добавление записи в БД выполнялись в транзакции

2024-04-29 08:14 UTC, Aidamir approved these changes

2024-05-08 18:25 UTC, merged